node {
    
   stage ('Checkout') {
      git url: 'https://github.com/codeurjc/curso-ci.git'
   }

   stage ('Build Java') {

      ARCHIVA_IP = sh (
        script: 'docker inspect -f \'{{.NetworkSettings.IPAddress }}\' archiva',
        returnStdout: true
      ).trim()

      docker.image('maven').inside('-v $HOME/.m2:/root/.m2') {

        sh 'cd ejem3; mvn package'

        sh 'cd ejem3; mvn deploy -DrepositoryId=archiva.snapshots -Durl=http://${ARCHIVA_IP}:8081/repository/snapshots/'
      }
   }

   stage ('Docker Image') {

      sh 'cd ejem3; ./build-image.sh'

      sh 'cd ejem3; docker push micaelgallego/curso-ci-ejem3:latest'
   }

  always {
      step([$class: 'JUnitResultArchiver', 
         testResults: '**/target/surefire-reports/TEST-*.xml'])
  }
}